# Generated by Django 5.2.4 on 2025-10-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=50)),
                ('describe', models.TextField()),
                ('image', models.ImageField(upload_to='project_image/')),
                ('Project_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
